import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";
import ProviderWrapper from "@/redux/ProviderWrapper"; // Import Redux provider
import SessionWrapper from "@/components/sessionWrapper"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sentinel Associates",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-screen flex flex-col bg-purple-950 text-white">
        <SessionWrapper>
          <ProviderWrapper>
            <Navbar />

            <main className="flex-1">
              {children}
            </main>

            <Footer />
          </ProviderWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}
